# ----------------------- #
# PATH CONFIGURATION FILE #
# ----------------------- #

dataset:
  images: "/path/to/images/"
  annotations: "/path/to/annotations/"
  split: "/path/to/split/"

experiment:
