# ----------- #
# STATISTICS  #
# ----------- #

# Min-Max
min_max:
  train:
    min: [0.0, 0.0, 0.0]
    max: [255.0, 255.0, 255.0]
  val:
    min: [0.0, 0.0, 0.0]
    max: [255.0, 255.0, 255.0]
  test:
    min: [0.0, 0.0, 0.0]
    max: [255.0, 255.0, 255.0]

# Standard deviation
std:
  train:
    mean: [0.485, 0.456, 0.406]
    std:  [0.229, 0.224, 0.225]
  val:
    mean: [0.485, 0.456, 0.406]
    std:  [0.229, 0.224, 0.225]
  test:
    mean: [0.5, 0.5, 0.5]
    std:  [0.25, 0.25, 0.25]
